### ISSUE TITLE
NameError: name 'Ethnicity' is not defined

### ISSUE THREAD

**Issue by ghost** [i9k/ethnicity#1]
https://imgur.com/a/POrsnFd

There is a error when i testing code which you specified at "Usage" part.

> python3 test.py
running make_dicts...
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    e = Ethnicity().make_dicts()
NameError: name 'Ethnicity' is not defined

**Comment by haixuanTao** [comment]
Change e to:
```
    e = ethnicity.Ethnicity().make_dicts()
```

**Comment by aNerdgirl** [comment]
> 
> 
> Change e to:
> 
> ```
>     e = ethnicity.Ethnicity().make_dicts()
> ```

I have the same problem. After changing the code to your suggestion, the following happens:

```
assert self.ETHNICITIES <= set(os.listdir(self.DATADIR)), '** error ** data is missing for some ethnicities!'
# map the included ethnicities to race

AssertionError: ** error ** data is missing for some ethnicities!
```

I highly appreciate your help!

**Comment by haixuanTao** [comment]
@aNerdgirl , I'm having trouble reproducing your error.

I would suggest:
- Reinstalling the package.
- Checking the folder outputed by: ```ethnicity.Ethnicity().DATADIR``` and make sure it exist and is not empty.
- Checking the actual assertion, which is that ```set(os.listdir(ethnicity.Ethnicity().DATADIR))``` is actually bigger than:

 ``` 
set("""indian japanese greek arabic turkish iranian 
thai vietnamese south-slavic italian samoan 
hawaiian khmer chinese korean polish fijian anglo-saxon german hispanic portuguese 
russian""".split())
``` 

- If not and the set you currently have is close enough, I would suggest getting rid of the assertion, but this should not happened. 

I'm not the author of the package, so that's my 2c. 

Hope it helps.

**Comment by aNerdgirl** [comment]
@haixuanTao thank you very very much for your fast and helpful reply.
`ethnicity.Ethnicity().DATADIR` always shows 
'''
AssertionError: ** error ** data is missing for some ethnicities!
'''

I think my error is with my file structure. `ethnicity.Ethnicity().DATADIR` demands a data folder. The data folder is in the main dir, where I also execute the code.
but does the content need to be similar structures as in the git repository (Country - First Name / Last Name / Full Name)?
because right now, I tried the exact same structure, which didnt work. but also a list of txt files with the country as title.

please excuse my stupidity, but it isn't really clear how the datadir should actually look like.

**Comment by haixuanTao** [comment]
Ah yes, sorry. The function ```ethnicity.Ethnicity``` can not be initialized in your case.

So ```DATADIR``` is the directory of the package ethnicity. For me it is the following on Linux Ubuntu:
```
'/home/USER/anaconda3/lib/python3.7/site-packages/ethnicity/data'
```

It has to be similar in folder organization. Yes.
Country should contain folder, I suppose.

No one is stupid here, don't worry :)

**Comment by aNerdgirl** [comment]
@haixuanTao  thank you so much for your help. I finally figured it out!
I am very happy, that this community is so helpful! Thank you!

**Comment by ghost** [comment]
Thanks guys...
